[package]
name = "nothing-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "nothing"
path = "src/main.rs"

[dependencies]
nothing-core = { path = "../core" }
nothing-action = { path = "../action" }
nothing-eval = { path = "../eval" }
nothing-store = { path = "../store" }
nothing-stdlib = { path = "../stdlib" }
nothing-tui = { path = "../tui" }
nothing-merge = { path = "../merge" }
nothing-agentapi = { path = "../agentapi" }

[dev-dependencies]
libc = "0.2"
crossterm = "0.29.0"
