use std::path::Path;

use nothing_core::docs::DocTable;
use nothing_core::names::NameTable;
use nothing_store::Document;
use nothing_tui::beginner::{phrase, ty_phrase};

use crate::fileio::read_document;

pub const HELP: &str = "\
nothing doc [<file>] [-o <out>]

Render a document as a static reference: one section per definition with its
name, its type, its doc line, and its body in the beginner projection. With
no <file>, the embedded standard library is rendered.

Output is Markdown on standard output, or written to <out> with `-o`.

Options:
  -o <out>     write the reference to <out> instead of standard output
  -h, --help   print this help and exit";

pub fn render_reference(title: &str, doc: &Document) -> String {
    let names = &nothing_stdlib::prelude().names_for(&doc.names);
    let docs = &doc.docs;
    let mut out = String::new();
    out.push_str(&format!("# {title}\n\n"));
    out.push_str(&format!(
        "{} definitions. Generated by `nothing doc`; do not edit by hand.\n\n",
        doc.doc.len()
    ));

    out.push_str("| name | type | what it is |\n|---|---|---|\n");
    for def in doc.doc.defs() {
        out.push_str(&format!(
            "| [`{}`](#{}) | `{}` | {} |\n",
            names.display(def.id),
            anchor(&names.display(def.id)),
            def.ann,
            docs.get(def.id).unwrap_or("—")
        ));
    }
    out.push('\n');

    for def in doc.doc.defs() {
        out.push_str(&section(def.id, &def.ann, &def.body, names, docs));
    }
    out
}

fn anchor(name: &str) -> String {
    name.chars()
        .filter(|c| c.is_alphanumeric() || *c == '_' || *c == '-')
        .flat_map(char::to_lowercase)
        .collect()
}

fn section(
    id: nothing_core::exp::Id,
    ann: &nothing_core::ty::Ty,
    body: &nothing_core::exp::Exp,
    names: &NameTable,
    docs: &DocTable,
) -> String {
    let name = names.display(id);
    let mut out = String::new();
    out.push_str(&format!("### `{name}`\n\n"));
    out.push_str(&format!("{}\n\n", docs.get(id).unwrap_or("Undocumented.")));
    out.push_str(&format!("**Type** `{ann}` — {}\n\n", ty_phrase(ann)));
    out.push_str("```\n");
    out.push_str(&format!(
        "{name} : {} = {}\n",
        ann,
        nothing_core::render::render(body, names)
    ));
    out.push_str("```\n\n");
    out.push_str("In words: ");
    out.push_str(&phrase(body, names));
    out.push_str(".\n\n");
    out
}

pub fn stdlib_reference() -> String {
    render_reference("The `nothing` standard library", nothing_stdlib::document())
}

pub fn run(path: Option<&Path>, out: Option<&Path>) -> i32 {
    let text = match path {
        None => stdlib_reference(),
        Some(path) => match read_document(path) {
            Ok(document) => render_reference(&format!("`{}`", path.display()), &document),
            Err(err) => {
                eprintln!("error: {err}");
                return 1;
            }
        },
    };

    match out {
        None => {
            print!("{text}");
            0
        }
        Some(out) => match std::fs::write(out, &text) {
            Ok(()) => {
                eprintln!("wrote {} bytes to {}", text.len(), out.display());
                0
            }
            Err(err) => {
                eprintln!("error: cannot write {}: {err}", out.display());
                1
            }
        },
    }
}
